package uz.toshshahartransxizmat.toshbustravel.util

// Example string resources
val enStrings = mapOf(
    "welcome" to "Welcome",
    "select_language" to "Select Language",
    "login" to "Login",
    "phone_number" to "Phone Number",
    "password" to "Password",
    "no_account" to "Don't have an account?",
    "register" to "Register",
    "forgot_password" to "Forgot Password",
    "continue" to "Continue",
    "enter_phone_number" to "Enter phone number",
    "enter_password" to "Enter password",
    "enter_at_least_4_characters" to "Enter at least 4 characters",
    "full_name" to "Full Name",
    "enter_full_name" to "Enter Full Name",
    "confirm_password" to "Confirm Password",
    "have_account" to "Already have an account?",
    "sign_in" to "Sign In",
    "sms_verification" to "SMS Verification",
    "sent_to_number" to "Sent to number",
    "resend" to "Resend",
    "retry_in" to "Retry in",
    "passwords_do_not_match" to "Passwords do not match",
    "available_cars" to "Available Cars",
    "best_quality_booking" to "Best Quality Booking",
    "learn_more" to "Learn More",
    "create_password" to "Create Password",
    "number_of_seats" to "Number of Seats",
    "seats" to "Seats",
    "amenities" to "Amenities",
    "booked" to "Booked",
    "your_orders" to "Your Orders",
    "profile" to "Profile",
    "edit_profile" to "Edit Profile",
    "language" to "Language",
    "log_out" to "Log Out",
    "view_total_amount" to "View Total Amount",
    "total_distance" to "Total Distance:",
    "select_order_type" to "Select Order Type:",
    "order_within_city" to "Order within the city",
    "order_outside_city" to "Order outside the city",
    "enter_date_time_for_order" to "Enter Date and Time for Your Order:",
    "start_date" to "Start Date",
    "start_time" to "Start Time",
    "end_date" to "End Date",
    "end_time" to "End Time",
    "total_time" to "Total Time:",
    "payment" to "Payment",
    "card_number" to "Card Number",
    "card_expiry" to "Card Expiry",
    "amount_due" to "Amount Due:",
    "sum" to "sum",
    "your_request_will_be_processed_for_this_amount" to "Your request will be processed for this amount",
    "cancel" to "Cancel",
    "confirm" to "Confirm",
    "pay" to "Pay",
    "processing" to "Processing",
    "check_status" to "Check Status",
    "the_request_will_be_processed_in_a_few_minutes" to "The request will be processed in a few minutes",
    "technical_error_try_again_later" to "Technical error, try again later",
    "my_location" to "My Location",
    "from" to "From",
    "to" to "To",
    "payment_successful" to "Payment was successfully completed",
    "track_order_status" to "You can track your order status in the app's orders section.",
    "track_order_status_two" to "If there is a delay in your order, contact the service provider's support!",
    "view_order" to "View Order",
    "receipt" to "Receipt",
    "add_cards" to "Add Cards",
    "active_card_tip" to "A card with active money inflows will increase the chance of approval",
    "choose_card" to "Choose Card",
    "add_new" to "Add new",
    "note" to "Note! If you want to add a VISA or MasterCard, you must enter the full card details!"
)
