package uz.toshshahartransxizmat.toshbustravel.util

val ruStrings = mapOf(
    "welcome" to "Добро пожаловать",
    "select_language" to "Выберите язык",
    "login" to "Вход",
    "phone_number" to "Номер телефона",
    "password" to "Пароль",
    "no_account" to "У вас нет аккаунта?",
    "register" to "Регистрация",
    "forgot_password" to "Забыл пароль",
    "continue" to "Продолжить",
    "enter_phone_number" to "Введите номер телефона",
    "enter_password" to "Введите пароль",
    "enter_at_least_4_characters" to "Введите не менее 4 символов",
    "full_name" to "ФИО",
    "enter_full_name" to "Введите ФИО",
    "confirm_password" to "Подтвердите пароль",
    "have_account" to "У вас есть аккаунт?",
    "sign_in" to "Войти",
    "sms_verification" to "СМС-подтверждение",
    "sent_to_number" to "Отправили на номер",
    "resend" to "Отправить еще раз",
    "retry_in" to "Повтор через",
    "passwords_do_not_match" to "Пароли не совпадают",
    "available_cars" to "Свободные машины",
    "best_quality_booking" to "Бронирование лучшего качества",
    "learn_more" to "Подробнее",
    "create_password" to "Создать пароль",
    "number_of_seats" to "Кол-во мест",
    "seats" to "мест",
    "amenities" to "Удобства",
    "booked" to "Бронирован",
    "your_orders" to "Ваши заказы",
    "profile" to "Профиль",
    "edit_profile" to "Редактировать профиль",
    "language" to "Язык",
    "log_out" to "Выйти",
    "view_total_amount" to "Посмотреть сумму",
    "total_distance" to "Общее расстояние:",
    "select_order_type" to "Выберите тип заказа:",
    "order_within_city" to "Заказ внутри города",
    "order_outside_city" to "Заказ за городом",
    "enter_date_time_for_order" to "Введите дату и время для вашего заказа:",
    "start_date" to "Дата начала",
    "start_time" to "Время начала",
    "end_date" to "Дата окончания",
    "end_time" to "Время окончания",
    "total_time" to "Общее время:",
    "payment" to "Оплата",
    "card_number" to "Номер карты",
    "card_expiry" to "Срок карты",
    "amount_due" to "Сумма к оплате:",
    "sum" to "сум",
    "your_request_will_be_processed_for_this_amount" to "Ваша заявка будет обработана за эту сумму",
    "cancel" to "Отменить",
    "confirm" to "Подтвердить",
    "pay" to "Оплатить",
    "processing" to "Обрабатывается",
    "check_status" to "Проверить статус",
    "the_request_will_be_processed_in_a_few_minutes" to "Для обработки заявки потребуется несколько минут",
    "technical_error_try_again_later" to "Техническая ошибка, попробуйте позже"
)
