package uz.toshshahartransxizmat.toshbustravel.util

val uzStrings = mapOf(
    "welcome" to "Xush kelibsiz",
    "select_language" to "Til tanlang",
    "login" to "Kirish",
    "phone_number" to "Telefon raqam",
    "password" to "Parol",
    "no_account" to "Akkauntingiz yo'qmi?",
    "register" to "Ro'yxatdan o'tish",
    "forgot_password" to "Parolni unutdingizmi",
    "continue" to "Davom etish",
    "enter_phone_number" to "Telefon raqamni kiriting",
    "enter_password" to "Parolni kiriting",
    "enter_at_least_4_characters" to "Kamida 4 ta belgi kiriting",
    "full_name" to "F.I.Sh.",
    "enter_full_name" to "F.I.Sh. ni kiriting",
    "confirm_password" to "Parolni tasdiqlang",
    "have_account" to "Akkauntingiz bormi?",
    "sign_in" to "Kirish",
    "sms_verification" to "SMS orqali tasdiqlash",
    "sent_to_number" to "Raqamga yuborildi",
    "resend" to "Qayta yuborish",
    "retry_in" to "Qayta urinish",
    "passwords_do_not_match" to "Parollar mos emas",
    "available_cars" to "Bo'sh mashinalar",
    "best_quality_booking" to "Eng sifatli bron qilish",
    "learn_more" to "Batafsil",
    "create_password" to "Parol yaratish",
    "number_of_seats" to "O‘rinlar soni",
    "seats" to "O‘rinlar",
    "amenities" to "Qulayliklar",
    "booked" to "Band qilingan",
    "your_orders" to "Buyurtmalaringiz",
    "profile" to "Profil",
    "edit_profile" to "Profilni tahrirlash",
    "language" to "Til",
    "log_out" to "Chiqish",
    "view_total_amount" to "Summani ko'rish",
    "total_distance" to "Umumiy masofa:",
    "select_order_type" to "Buyurtma turini tanlang:",
    "order_within_city" to "Shahar ichida buyurtma",
    "order_outside_city" to "Shahar tashqarisida buyurtma",
    "enter_date_time_for_order" to "Buyurtma uchun sana va vaqtni kiriting:",
    "start_date" to "Boshlanish sanasi",
    "start_time" to "Boshlanish vaqti",
    "end_date" to "Tugatish sanasi",
    "end_time" to "Tugatish vaqti",
    "total_time" to "Umumiy vaqt:",
    "payment" to "To'lov",
    "card_number" to "Karta raqami",
    "card_expiry" to "Karta muddati",
    "amount_due" to "To'lanadigan summa:",
    "sum" to "sum",
    "your_request_will_be_processed_for_this_amount" to "Sizning so'rovingiz ushbu summa uchun qayta ishlanadi",
    "cancel" to "Bekor qilish",
    "confirm" to "Tasdiqlang",
    "pay" to "To'lash"
)
